config/routes.rb
Rails.application.routes.draw do
  get 'favorites/index'
  get 'favorites/create'
  get 'favorites/destroy'
  get 'users/show'
  root 'pages#index'
  get 'pages/help'

  devise_for :users
  resources :topic_us do
    resources :topic_ds
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  
  def topic
    if self.topic_type == "above"
      TopicU.find_by(id: self.topic_id)
    else
      TopicD.find_by(id: self.topic_id)
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = []
    current_user.favorites.each do |favorite|
      @favorite_topics << favorite.topic
    end
    @favorite_topics.reverse!
  end

  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    favorite.topic_type = params[:topic_type]
    
    if favorite.save
      redirect_back(fallback_location: root_path, success: 'お気に入りしました')
    else
      redirect_to root_path, danger: 'お気に入りできませんでした'
    end
  end

  def destroy
    Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id], topic_type: params[:topic_type]).destroy
      redirect_back(fallback_location: root_path)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/index.html.erb
<div class="top-hero-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card container">
          <div class="card-body">
            <% if topic.instance_of?(TopicD) %>
              <% if topic.topic_u.present? %>
                <p><%= topic.topic_u.text %></p>
              <% else %>
                <p>この投稿は表示できません</p>
              <% end %>
            <% end %>
            <h5 class="card-title"><%= link_to topic.text, topic_u_path(id: topic.id) %></h5>
            <p><%= topic.created_at %></p>
            <% if topic.instance_of?(TopicU) %>
              <%= link_to '下の句投稿', new_topic_u_topic_d_path(topic_u_id: topic.id) %>
              <%= topic.topic_ds.count %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>