config/routes.rb
Rails.application.routes.draw do
  get 'favorites/index'
  get 'favorites/create'
  get 'favorites/destroy'
  get 'users/show'
  root 'pages#index'
  get 'pages/help'

  devise_for :users
  resources :topic_us do
    resources :topic_ds
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic_d.rb
class TopicD < ApplicationRecord
  validates :user_id, :topic_u_id, :text, presence: true
  
  belongs_to :user
  belongs_to :topic_u
  
  def favorite_ds_ids
    Favorite.where(topic_id: self.id, topic_type: "lower").pluck(:user_id)
  end
end

app/controllers/topic_ds_controller.rb
class TopicDsController < ApplicationController
  def index
    @topic_ds = TopicD.all
  end
    
  def new
    @topic_d = TopicD.new
    @topic_u = TopicU.find(params[:topic_u_id])
  end

  def create
    @topic_d = current_user.topic_ds.new(topic_d_params)
    @topic_d.topic_u_id = params[:topic_u_id]
    if @topic_d.save
      redirect_to topic_u_path(id: params[:topic_u_id])
    else
      render :new
    end
  end

  def show
    @topic_u = TopicU.find(params[:topic_u_id])
  end
  
  def destroy
    @topic_d = TopicD.find(params[:id])
    if @topic_d.delete
      redirect_to root_path
    else
      redirect_to topic_d_path
    end
  end

  private
  def topic_d_params
    params.require(:topic_d).permit(:text)
  end
end

app/helpers/topic_ds_helper.rb
module TopicDsHelper
end

app/views/topic_ds/create.html.erb
<h1>TopicDs#create</h1>
<p>Find me in app/views/topic_ds/create.html.erb</p>

app/views/topic_ds/new.html.erb
<%= form_for [@topic_u, @topic_d] do |f| %>
  <%= f.label "下の句" %>
  <%= f.text_field :text %>
  <%= f.submit "投稿" %>
<% end %>

app/views/topic_ds/show.html.erb
<div class="top-hero-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card container">
          <div class="card-body">
            <h5 class="card-title"><%= @topic_u.text %></h5>
            <p class="card-text"><%= @topic_u.created_at %></p>
            <% @topic_u.topic_ds.each do |topic_d| %>
              <h6 class="card-subtitle mb-2 text-muted"><%= link_to topic_d.text, topic_u_topic_d_path(id: topic_d.id) %></h6>
              <p class="card-text"><%= topic_d.created_at %></p>
            <% end %>
            <% if user_signed_in? %>
              <a class="card-link"><%= link_to '削除', topic_u_path(id: @topic_u.id), method: :delete %></a>
              <a class="card-link"><%= link_to '下の句投稿', new_topic_u_topic_d_path(topic_u_id: @topic_u.id) %></a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>