config/routes.rb
Rails.application.routes.draw do
  get 'favorites/index'
  get 'favorites/create'
  get 'favorites/destroy'
  get 'users/show'
  root 'pages#index'
  get 'pages/help'

  devise_for :users
  resources :topic_us do
    resources :topic_ds
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  
  def topic
    if self.topic_type == "above"
      TopicU.find_by(id: self.topic_id)
    else
      TopicD.find_by(id: self.topic_id)
    end
  end
end

app/models/topic_d.rb
class TopicD < ApplicationRecord
  validates :user_id, :topic_u_id, :text, presence: true
  
  belongs_to :user
  belongs_to :topic_u
  
  def favorite_ds_ids
    Favorite.where(topic_id: self.id, topic_type: "lower").pluck(:user_id)
  end
end

app/models/topic_u.rb
class TopicU < ApplicationRecord
  validates :user_id, :text, presence: true
  
  belongs_to :user
  has_many :topic_ds
  
  def favorite_us_ids
    Favorite.where(topic_id: self.id, topic_type: "above").pluck(:user_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :topic_us
  has_many :topic_ds
  has_many :favorites
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = []
    current_user.favorites.each do |favorite|
      @favorite_topics << favorite.topic
    end
    @favorite_topics.reverse!
  end

  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    favorite.topic_type = params[:topic_type]
    
    if favorite.save
      redirect_back(fallback_location: root_path, success: 'お気に入りしました')
    else
      redirect_to root_path, danger: 'お気に入りできませんでした'
    end
  end

  def destroy
    Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id], topic_type: params[:topic_type]).destroy
      redirect_back(fallback_location: root_path)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @topic_us = TopicU.all.sort_by {|record| record.updated_at}.reverse!
  end
end

app/controllers/topic_ds_controller.rb
class TopicDsController < ApplicationController
  def index
    @topic_ds = TopicD.all
  end
    
  def new
    @topic_d = TopicD.new
    @topic_u = TopicU.find(params[:topic_u_id])
  end

  def create
    @topic_d = current_user.topic_ds.new(topic_d_params)
    @topic_d.topic_u_id = params[:topic_u_id]
    if @topic_d.save
      redirect_to topic_u_path(id: params[:topic_u_id])
    else
      render :new
    end
  end

  def show
    @topic_u = TopicU.find(params[:topic_u_id])
  end
  
  def destroy
    @topic_d = TopicD.find(params[:id])
    if @topic_d.delete
      redirect_to root_path
    else
      redirect_to topic_d_path
    end
  end

  private
  def topic_d_params
    params.require(:topic_d).permit(:text)
  end
end

app/controllers/topic_us_controller.rb
class TopicUsController < ApplicationController
  after_action :save_my_previous_url, only: [:new]

  def new
    @topic_u = TopicU.new
  end

  def create
    @topic_u = current_user.topic_us.new(topic_u_params)
    if @topic_u.save
      redirect_to session[:my_previous_url]
    else
      render :new
    end
  end

  def show
    @topic_u = TopicU.find_by(id: params[:id])
  end
  
  def destroy
    @topic_u = TopicU.find(params[:id])
    if @topic_u.delete
      redirect_to root_path
    else
      redirect_to topic_u_path
    end
  end
  
  private
    def save_my_previous_url
    # session[:previous_url] is a Rails built-in variable to save last url.
    session[:my_previous_url] = URI(request.referer || '').path
    end

    def topic_u_params
      params.require(:topic_u).permit(:text)
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
   def destroy
     super
   end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
   end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @topic_us =current_user.topic_us
    @topic_ds =current_user.topic_ds
    @topics = (@topic_us + @topic_ds).sort_by {|record| record.created_at}.reverse!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/topic_ds_helper.rb
module TopicDsHelper
end

app/helpers/topic_us_helper.rb
module TopicUsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hiku</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-expand-md navbar-fixed-top navbar-transparent">
      <div class = "container">
        <div class = "navbar-left">
        <h1 class = "logo">
        <%= link_to 'Hi! ku', root_path %>
        </h1>
        </div>
        <div class = "navbar-right">
        <% if !user_signed_in? %>
          <%= link_to 'Log in', new_user_session_path %>
          <%= link_to 'Sign in', new_user_registration_path %>
        <% else %>
          <%= link_to '投稿', new_topic_u_path %>
          <%= link_to 'user page', users_show_path %>
          <%= link_to 'favorite', favorites_index_path %>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
        <% end %>
        </div>
    </nav>
    
    <% flash.each do |key, value| %>
      <div class = "alert alert-<%= key %>" role = "alert"><%= value %></div>
    <% end %>
    
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
  </body>
</html>

app/views/pages/index.html.erb
<div class="top-hero-wrapper">
  <div class="container">
    <% @topic_us.each do |topic_u| %>
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card container">
          <div class="card-body">
            <h5 class="card-title"><%= link_to topic_u.text, topic_u_path(id: topic_u.id) %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= topic_u.user.name %></h6>
            <p class="card-text"><%= topic_u.created_at %></p>
            <% if user_signed_in? %>
              <% if topic_u.favorite_us_ids.include?(current_user.id) %>
                <a class="card-link"><%= link_to '︎♥', favorites_destroy_path(topic_id: topic_u.id, topic_type: "above") %></a>
              <% else %>
                <a class="card-link"><%= link_to '♡', favorites_create_path(topic_id: topic_u.id, topic_type: "above") %></a>
              <% end %>
            <% end %>
          </div>
         </div>
        </div>
      </div>
    <% end %>
  </div>
</div>